### ISSUE TITLE
python3 train.py  gives the following error: line 23, in find_classes FileNotFoundError: [Errno 2] No such file or directory: 'background'

### ISSUE THREAD

**Issue by Sumes** [fangpin/siamese-network#2]
python3 train.py  
gives the following error: 
Traceback (most recent call last):   File "train.py", line 29, in <module>     train_dataset = dset.ImageFolder(root=train_path)   File "/home/sumes/anaconda3/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/datasets/folder.py", line 178, in __init__   File "/home/sumes/anaconda3/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/datasets/folder.py", line 75, in __init__   File "/home/sumes/anaconda3/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/datasets/folder.py", line 23, in find_classes FileNotFoundError: [Errno 2] No such file or directory: 'background'

**Comment by fangpin** [comment]
@Sumes go into train.py and change the variable 'train_path' and 'test_path' to the path to your training and test data folder.
